### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by pranav0408** [sanudatta11/mshacks2.0-v3#1]
The Mobile Version and the Desktop Version of the website are not properly aligned to the screen.

**Comment by pranav0408** [comment]
The arrow to the top does not appear properly in mobile version of website too

**Comment by rowhitswami** [comment]
@pranav0408 are you on it?

**Comment by pranav0408** [comment]
The Desktop version is now aligned so I am closing this issue. I'll open another issue in case it is needed for mobile version.
